description: >
  Docker image for jq and cURL based on alpine image.
docker:
  - image: 'endeveit/docker-jq:<<parameters.tag>>'
parameters:
  tag:
    default: latest
    description: >
      Pick a specific endeveit/docker-jq image variant:
      https://hub.docker.com/r/endeveit/docker-jq/tags
    type: string
